# Generated by Django 3.1.6 on 2021-02-12 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_auto_20210212_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_id', models.SmallIntegerField(choices=[(0, 'увидеть задачу'), (1, 'сделать сабмит решения'), (2, 'решить задачу')], default=0)),
                ('time', models.DateTimeField()),
                ('target_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.user')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
