# Generated by Django 3.1.6 on 2021-02-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_event_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_guest',
            field=models.BooleanField(),
        ),
    ]
