# Generated by Django 3.1.6 on 2021-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_auto_20210213_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
