# Generated by Django 3.1.6 on 2021-02-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_auto_20210213_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='target_id',
            new_name='target',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='user_id',
            new_name='user',
        ),
    ]
