# Generated by Django 3.1.6 on 2021-02-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_auto_20210214_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producerlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_id', models.IntegerField()),
                ('max_id', models.IntegerField()),
                ('ts', models.DateTimeField(auto_now=True)),
                ('producer_id', models.CharField(max_length=255)),
                ('status', models.BinaryField(default=0)),
                ('has_errors', models.BinaryField(default=0)),
            ],
            options={
                'ordering': ('min_id',),
            },
        ),
    ]
